server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
  #表示不能再用microservicecloud-dept服务名，需要使用mydept服务名，我们也可以使用"*"表示禁用所有的微服务真实名称
  #ignored-services: microservicecloud-dept  
  prefix: /gh #访问路径加上前缀gh，http://127.0.0.1:9527/gh/mydept/dept/get/1
  ignored-services: "*"
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
 
info:
  app.name: gh-microcloud
  company.name: www.gh.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

